server:
  port: 10010
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://47.112.196.76:9100/rtm?useUnicode=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/rtm?useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: qq
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1